### ISSUE TITLE
define gems, npms and composer in the default.yml

### ISSUE THREAD

**Issue by miya0001** [vccw-team/vccw#144]
Move following into `default.yml`.

```
  vars:
    wp_cli_bin_url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    rubygems:
      - bundler
      - wordmove
      - mailcatcher
    npms:
      - gulp-cli
      # - grunt-init
      # - grunt-cli
    composers:
      - hirak/prestissimo:*
      - phpunit/phpunit:*
      - squizlabs/php_codesniffer:*
      - wp-coding-standards/wpcs:*
      # - phpmd/phpmd:*
      # - sebastian/phpcpd:*
      # - phploc/phploc:*
      # - phing/phing:*
```
